name: build osx package

inputs:
  is_tag:
    description: 'Is a Git Tag'
    required: true
  current_branch_tag:
    description: 'Git branch or Tag'
    required: true
  stable_unstalbe:
    description: 'stable/unstable'
    required: true

runs:
  using: "composite"

  steps:
  - name: Build OSX Package
    shell: bash
    run: ./build-osx-package.sh is_tag=${{ inputs.is_tag }} version=${{ inputs.stable_unstable }} branchTagName=${{ inputs.current_branch_tag }}
