######################################
ARG IMAGE_UNDER_TEST=orthancteam/orthanc:latest
FROM $IMAGE_UNDER_TEST

RUN apt-get update
RUN	DEBIAN_FRONTEND=noninteractive apt-get --assume-yes install dcmtk mercurial
RUN pip install httplib2 --break-system-package
RUN pip install pillow --break-system-package

WORKDIR /

COPY ./orthanc-tests-repo /orthanc-tests


ENTRYPOINT python3 /orthanc-tests/Tests/CheckIngestTranscoding.py /usr/local/bin/Orthanc
