version: "3"
services:
  orthanc-under-tests:
    image: orthanc-under-tests
    environment:
      # VERBOSE_STARTUP: "true"
      # VERBOSE_ENABLED: "true"
      GDCM_PLUGIN_ENABLED: "false"

  orthanc-tests-dicomweb:
    image: orthanc-tests-dicomweb
    depends_on:
      - orthanc-under-tests

