services:
  orthanc-under-tests:
    image: orthanc-under-tests
    depends_on:
      s3-like:
        condition: service_healthy
    environment:
      ORTHANC__AWS_S3_STORAGE__BUCKET_NAME: "my-sample-bucket"
      ORTHANC__AWS_S3_STORAGE__REGION: "eu-west-1"
      ORTHANC__AWS_S3_STORAGE__ACCESS_KEY: "s3-like-admin"
      ORTHANC__AWS_S3_STORAGE__SECRET_KEY: "change-me"
      ORTHANC__AWS_S3_STORAGE__ENDPOINT: "http://s3-like:8333"
      ORTHANC__AWS_S3_STORAGE__VIRTUAL_ADDRESSING: "false"
      # VERBOSE_ENABLED: "true"

  orthanc-tests:
    image: orthanc-tests
    depends_on:
      orthanc-under-tests:
        condition: service_started

  s3-like:
    image: chrislusf/seaweedfs
    ports: [8333:8333]
    environment:
      - AWS_ACCESS_KEY_ID=s3-like-admin
      - AWS_SECRET_ACCESS_KEY=change-me
      - S3_BUCKET=my-sample-bucket
    command: mini -dir=/data
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:9333/cluster/healthz"]
      interval: 2s
      timeout: 1s
      retries: 3

