FROM osimis/orthanc:17.5.alpha

RUN apt-get update \ 
&& DEBIAN_FRONTEND=noninteractive apt-get -y install \
unixodbc

COPY binaries/plugins-pro/ /usr/share/orthanc/plugins

COPY mssql.json /etc/orthanc/

