########################## Orthanc builder base
# image to compile Orthanc and its plugins dynamically
ARG BASE_IMAGE_TAG=current
FROM orthancteam/orthanc-runner-base:${BASE_IMAGE_TAG}

RUN export DEBIAN_FRONTEND=noninteractive
RUN apt-get --assume-yes update
RUN apt-get --assume-yes install wget
RUN apt-get --assume-yes install build-essential
RUN apt-get --assume-yes install unzip
RUN apt-get --assume-yes install uuid-dev
RUN apt-get --assume-yes install apt-utils
RUN apt-get --assume-yes install libcurl4-openssl-dev
RUN apt-get --assume-yes install curl
RUN apt-get --assume-yes install apt-transport-https
RUN apt-get --assume-yes install liblua5.4-dev
RUN apt-get --assume-yes install libgtest-dev
RUN apt-get --assume-yes install libpng-dev
RUN apt-get --assume-yes install libsqlite3-dev
RUN apt-get --assume-yes install libjpeg-dev zlib1g-dev libdcmtk-dev libboost-all-dev libwrap0-dev libcharls-dev libjsoncpp-dev libpugixml-dev
RUN apt-get --assume-yes install git
RUN apt-get --assume-yes install mercurial
RUN apt-get --assume-yes install zip
RUN apt-get --assume-yes install libpq-dev postgresql-server-dev-all
RUN apt-get --assume-yes install python3-dev
RUN apt-get --assume-yes install unixodbc-dev
RUN apt-get --assume-yes install libgmock-dev
RUN apt-get --assume-yes install protobuf-compiler
# on recent Debian, the libmysql-dev package is not available anymore
# and the MariaDbConfiguration.cmake does not handle it correctly -> use the downloaded mariadb_client
RUN apt-get --assume-yes install default-libmysqlclient-dev
# RUN apt-get --assume-yes install libmariadb-dev

RUN apt-get --assume-yes install cmake
RUN apt-get --assume-yes install awscli
# for orthanc-stl plugin:
RUN apt-get --assume-yes install libgl1-mesa-dev libxt-dev

RUN apt-get --assume-yes install default-jdk

# # install a recent cmake version (required later by recent vcpkg versions that we don't use now !)
# WORKDIR /tmp
# RUN wget https://github.com/Kitware/CMake/releases/download/v3.23.1/cmake-3.23.1.tar.gz
# RUN tar -zxvf cmake-3.23.1.tar.gz
# WORKDIR /tmp/cmake-3.23.1
# RUN ./bootstrap
# RUN make -j 8
# RUN make install
RUN cmake --version

# no need to clean apt-cache, it's a build image, we don't care about its size

RUN mkdir -p /sources
RUN mkdir -p /build
RUN mkdir -p /scripts
RUN mkdir -p /third-party-downloads

# download most commonly used third-party files to avoid downloading too many files from UCLouvain servers when building
WORKDIR /third-party-downloads
RUN wget https://public-files.orthanc.team/third-party-downloads/VolView-4.1.1.tar.gz
RUN wget https://public-files.orthanc.team/third-party-downloads/aws/aws-c-auth-0.7.1.tar.gz
RUN wget https://public-files.orthanc.team/third-party-downloads/aws/aws-c-cal-0.6.1.tar.gz
RUN wget https://public-files.orthanc.team/third-party-downloads/aws/aws-c-common-0.9.3.tar.gz
RUN wget https://public-files.orthanc.team/third-party-downloads/aws/aws-c-compression-0.2.17.tar.gz
RUN wget https://public-files.orthanc.team/third-party-downloads/aws/aws-c-event-stream-0.3.1.tar.gz
RUN wget https://public-files.orthanc.team/third-party-downloads/aws/aws-c-http-0.7.11.tar.gz
RUN wget https://public-files.orthanc.team/third-party-downloads/aws/aws-c-io-0.13.31.tar.gz
RUN wget https://public-files.orthanc.team/third-party-downloads/aws/aws-c-mqtt-0.9.5.tar.gz
RUN wget https://public-files.orthanc.team/third-party-downloads/aws/aws-c-s3-0.3.14.tar.gz
RUN wget https://public-files.orthanc.team/third-party-downloads/aws/aws-c-sdkutils-0.1.11.tar.gz
RUN wget https://public-files.orthanc.team/third-party-downloads/aws/aws-checksums-0.1.17.tar.gz
RUN wget https://public-files.orthanc.team/third-party-downloads/aws/aws-crt-cpp-0.24.1.tar.gz
RUN wget https://public-files.orthanc.team/third-party-downloads/aws/aws-sdk-cpp-1.11.178.tar.gz
RUN wget https://public-files.orthanc.team/third-party-downloads/boost_1_83_0_bcpdigest-1.12.2.tar.gz
RUN wget https://public-files.orthanc.team/third-party-downloads/boost_1_84_0_bcpdigest-1.12.3.tar.gz
RUN wget https://public-files.orthanc.team/third-party-downloads/boost_1_85_0_bcpdigest-1.12.4.tar.gz
RUN wget https://public-files.orthanc.team/third-party-downloads/curl-8.5.0.tar.gz
RUN wget https://public-files.orthanc.team/third-party-downloads/dcmtk-3.6.8.tar.gz
RUN wget https://public-files.orthanc.team/third-party-downloads/gdcm-3.0.22.tar.gz
RUN wget https://public-files.orthanc.team/third-party-downloads/jpegsrc.v9f.tar.gz
RUN wget https://public-files.orthanc.team/third-party-downloads/jsoncpp-1.9.5.tar.gz
RUN wget https://public-files.orthanc.team/third-party-downloads/libcsv-3.0.3.tar.gz
RUN wget https://public-files.orthanc.team/third-party-downloads/libpng-1.6.40.tar.gz
RUN wget https://public-files.orthanc.team/third-party-downloads/nifti_clib-3.0.0.tar.gz
RUN wget https://public-files.orthanc.team/third-party-downloads/openssl-3.1.4.tar.gz
RUN wget https://public-files.orthanc.team/third-party-downloads/protobuf-cpp-3.5.1.tar.gz
RUN wget https://public-files.orthanc.team/third-party-downloads/pugixml-1.14.tar.gz
RUN wget https://public-files.orthanc.team/third-party-downloads/three.js-r154-sources.tar.gz
RUN wget https://public-files.orthanc.team/third-party-downloads/VolView-4.1.1.tar.gz
RUN wget https://public-files.orthanc.team/third-party-downloads/VTK-7.1.1.tar.gz
RUN wget https://public-files.orthanc.team/third-party-downloads/zlib-1.3.1.tar.gz


COPY build-or-download.sh /scripts
