########################## Orthanc builder base
# image to compile Orthanc and its plugins dynamically
ARG BASE_IMAGE_TAG=current
FROM orthancteam/orthanc-runner-base:${BASE_IMAGE_TAG}

ARG PLATFORM=linux/amd64

RUN export DEBIAN_FRONTEND=noninteractive
RUN apt-get --assume-yes update
RUN apt-get --assume-yes install wget
RUN apt-get --assume-yes install build-essential
RUN apt-get --assume-yes install unzip
RUN apt-get --assume-yes install uuid-dev
RUN apt-get --assume-yes install apt-utils
RUN apt-get --assume-yes install libcurl4-openssl-dev
RUN apt-get --assume-yes install curl
RUN apt-get --assume-yes install apt-transport-https
RUN apt-get --assume-yes install liblua5.4-dev
RUN apt-get --assume-yes install libgtest-dev
RUN apt-get --assume-yes install libpng-dev
RUN apt-get --assume-yes install libsqlite3-dev
RUN apt-get --assume-yes install libjpeg-dev libboost-all-dev libwrap0-dev libcharls-dev libjsoncpp-dev libpugixml-dev
RUN apt-get --assume-yes install git
RUN apt-get --assume-yes install mercurial
RUN apt-get --assume-yes install zip
RUN apt-get --assume-yes install libpq-dev postgresql-server-dev-all
RUN apt-get --assume-yes install python3-dev
RUN apt-get --assume-yes install unixodbc-dev
RUN apt-get --assume-yes install libgmock-dev
RUN apt-get --assume-yes install protobuf-compiler
RUN apt-get --assume-yes install default-libmysqlclient-dev
RUN apt-get --assume-yes install zlib1g-dev


RUN apt-get --assume-yes install cmake
# RUN apt-get --assume-yes install awscli
RUN if [ "$PLATFORM" = "linux/amd64" ]; then curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "/tmp/awscliv2.zip"; fi
RUN if [ "$PLATFORM" = "linux/arm64" ]; then curl "https://awscli.amazonaws.com/awscli-exe-linux-aarch64.zip" -o "/tmp/awscliv2.zip"; fi
WORKDIR /tmp
RUN unzip awscliv2.zip
RUN ./aws/install

# for orthanc-stl plugin:
RUN apt-get --assume-yes install libgl1-mesa-dev libxt-dev

RUN apt-get --assume-yes install default-jdk

# for orthanc-wsi and orthanc-education plugins:
RUN apt-get --assume-yes install libopenslide0

# # install a recent cmake version (required later by recent vcpkg versions that we don't use now !)
# WORKDIR /tmp
# RUN wget https://github.com/Kitware/CMake/releases/download/v3.23.1/cmake-3.23.1.tar.gz
# RUN tar -zxvf cmake-3.23.1.tar.gz
# WORKDIR /tmp/cmake-3.23.1
# RUN ./bootstrap
# RUN make -j 8
# RUN make install
RUN cmake --version

# no need to clean apt-cache, it's a build image, we don't care about its size

RUN mkdir -p /sources
RUN mkdir -p /build
RUN mkdir -p /scripts
RUN mkdir -p /third-party-downloads

# download most commonly used third-party files to avoid downloading too many files from UCLouvain servers when building
WORKDIR /third-party-downloads
RUN wget https://public-files.orthanc.team/third-party-downloads/3DHOP_4.3.zip && \
    wget https://public-files.orthanc.team/third-party-downloads/aws/aws-c-auth-0.7.22.tar.gz && \
    wget https://public-files.orthanc.team/third-party-downloads/aws/aws-c-cal-0.7.0.tar.gz && \
    wget https://public-files.orthanc.team/third-party-downloads/aws/aws-c-common-0.9.23.tar.gz && \
    wget https://public-files.orthanc.team/third-party-downloads/aws/aws-c-compression-0.2.18.tar.gz && \
    wget https://public-files.orthanc.team/third-party-downloads/aws/aws-c-event-stream-0.4.2.tar.gz && \
    wget https://public-files.orthanc.team/third-party-downloads/aws/aws-c-http-0.8.2.tar.gz && \
    wget https://public-files.orthanc.team/third-party-downloads/aws/aws-c-io-0.14.9.tar.gz && \
    wget https://public-files.orthanc.team/third-party-downloads/aws/aws-c-mqtt-0.10.4.tar.gz && \
    wget https://public-files.orthanc.team/third-party-downloads/aws/aws-c-s3-0.5.10.tar.gz && \
    wget https://public-files.orthanc.team/third-party-downloads/aws/aws-c-sdkutils-0.1.16.tar.gz && \
    wget https://public-files.orthanc.team/third-party-downloads/aws/aws-checksums-0.1.18.tar.gz && \
    wget https://public-files.orthanc.team/third-party-downloads/aws/aws-crt-cpp-0.24.1.tar.gz && \
    wget https://public-files.orthanc.team/third-party-downloads/aws/aws-sdk-cpp-1.11.178.tar.gz && \
    wget https://public-files.orthanc.team/third-party-downloads/axios-0.19.0.tar.gz && \
    wget https://public-files.orthanc.team/third-party-downloads/babel-polyfill-6.26.0.min.js.gz && \
    wget https://public-files.orthanc.team/third-party-downloads/boost_1_83_0_bcpdigest-1.12.2.tar.gz && \
    wget https://public-files.orthanc.team/third-party-downloads/boost_1_84_0_bcpdigest-1.12.3.tar.gz && \
    wget https://public-files.orthanc.team/third-party-downloads/boost_1_85_0_bcpdigest-1.12.4.tar.gz && \
    wget https://public-files.orthanc.team/third-party-downloads/boost_1_86_0_bcpdigest-1.12.5.tar.gz && \
    wget https://public-files.orthanc.team/third-party-downloads/boost_1_89_0_bcpdigest-1.12.11.tar.gz  && \
    wget https://public-files.orthanc.team/third-party-downloads/bootstrap-4.3.1.zip && \
    wget https://public-files.orthanc.team/third-party-downloads/bootstrap-5.3.3.zip && \
    wget https://public-files.orthanc.team/third-party-downloads/civetweb-1.16-fixed.tar.gz && \
    wget https://public-files.orthanc.team/third-party-downloads/cornerstone-0.11.0.zip && \
    wget https://public-files.orthanc.team/third-party-downloads/curl-8.5.0.tar.gz && \
    wget https://public-files.orthanc.team/third-party-downloads/curl-8.9.0.tar.gz && \
    wget https://public-files.orthanc.team/third-party-downloads/curl-8.17.0.tar.gz && \
    wget https://public-files.orthanc.team/third-party-downloads/dcmtk-3.6.8.tar.gz && \
    wget https://public-files.orthanc.team/third-party-downloads/dcmtk-3.6.9.tar.gz && \
    wget https://public-files.orthanc.team/third-party-downloads/dcmtk-3.7.0.tar.gz && \
    wget https://public-files.orthanc.team/third-party-downloads/e2fsprogs-1.44.5.tar.gz && \
    wget https://public-files.orthanc.team/third-party-downloads/Font-Awesome-4.7.0.tar.gz && \
    wget https://public-files.orthanc.team/third-party-downloads/gdcm-3.0.22.tar.gz && \
    wget https://public-files.orthanc.team/third-party-downloads/jpegsrc.v9f.tar.gz && \
    wget https://public-files.orthanc.team/third-party-downloads/jquery-3.4.1.min.js && \
    wget https://public-files.orthanc.team/third-party-downloads/jquery-ui-1.11.3.zip && \
    wget https://public-files.orthanc.team/third-party-downloads/jsoncpp-1.9.5.tar.gz && \
    wget https://public-files.orthanc.team/third-party-downloads/jsPanel-2.3.3-fixed.zip && \
    wget https://public-files.orthanc.team/third-party-downloads/js-url-1.8.6.zip && \
    wget https://public-files.orthanc.team/third-party-downloads/libcsv-3.0.3.tar.gz && \
    wget https://public-files.orthanc.team/third-party-downloads/libpng-1.6.40.tar.gz && \
    wget https://public-files.orthanc.team/third-party-downloads/libpng-1.6.50.tar.gz && \
    wget https://public-files.orthanc.team/third-party-downloads/nexus-4.3.zip && \
    wget https://public-files.orthanc.team/third-party-downloads/nifti_clib-3.0.0.tar.gz && \
    wget https://public-files.orthanc.team/third-party-downloads/Online3DViewer-0.12.0.tar.gz && \
    wget https://public-files.orthanc.team/third-party-downloads/orthanc-framework/Orthanc-1.12.3.tar.gz && \
    wget https://public-files.orthanc.team/third-party-downloads/orthanc-framework/Orthanc-1.12.4.tar.gz && \
    wget https://public-files.orthanc.team/third-party-downloads/orthanc-framework/Orthanc-1.12.5.tar.gz && \
    wget https://public-files.orthanc.team/third-party-downloads/orthanc-framework/Orthanc-1.12.6.tar.gz && \
    wget https://public-files.orthanc.team/third-party-downloads/orthanc-framework/Orthanc-1.12.7.tar.gz && \
    wget https://public-files.orthanc.team/third-party-downloads/orthanc-framework/Orthanc-1.12.8.tar.gz && \
    wget https://public-files.orthanc.team/third-party-downloads/orthanc-framework/Orthanc-1.12.9.tar.gz && \
    wget https://public-files.orthanc.team/third-party-downloads/orthanc-framework/Orthanc-1.12.10.tar.gz && \
    wget https://public-files.orthanc.team/third-party-downloads/orthanc-framework/Orthanc-1.12.11.tar.gz && \    
    wget https://public-files.orthanc.team/third-party-downloads/orthanc-framework/Orthanc-0ebe8cfd9bf7.tar.gz && \
    wget https://public-files.orthanc.team/third-party-downloads/orthanc-framework/Orthanc-56eb61c86f93.tar.gz && \
    wget https://public-files.orthanc.team/third-party-downloads/orthanc-framework/Orthanc-94c7f3784456.tar.gz && \
    wget https://public-files.orthanc.team/third-party-downloads/orthanc-framework/Orthanc-e0979326ac53.tar.gz && \
    wget https://public-files.orthanc.team/third-party-downloads/openlayers-10.6.1-package.tar.gz && \
    wget https://public-files.orthanc.team/third-party-downloads/openssl-3.1.4.tar.gz && \
    wget https://public-files.orthanc.team/third-party-downloads/pako-0.2.5.zip && \
    wget https://public-files.orthanc.team/third-party-downloads/pdfjs-2.5.207-dist.zip && \
    wget https://public-files.orthanc.team/third-party-downloads/popper-2.11.8.min.js.gz && \
    wget https://public-files.orthanc.team/third-party-downloads/postgresql-13.23.tar.gz && \
    wget https://public-files.orthanc.team/third-party-downloads/postgresql-18.1.tar.gz && \
    wget https://public-files.orthanc.team/third-party-downloads/protobuf-cpp-3.5.1.tar.gz && \
    wget https://public-files.orthanc.team/third-party-downloads/pugixml-1.14.tar.gz && \
    wget https://public-files.orthanc.team/third-party-downloads/reproc-14.2.5.tar.gz && \
    wget https://public-files.orthanc.team/third-party-downloads/sqlite-amalgamation-3460100.zip && \
    wget https://public-files.orthanc.team/third-party-downloads/sqlite-amalgamation-3500400.zip && \
    wget https://public-files.orthanc.team/third-party-downloads/three.js-r154-sources.tar.gz && \
    wget https://public-files.orthanc.team/third-party-downloads/three-84.js.gz && \
    wget https://public-files.orthanc.team/third-party-downloads/VolView-4.4.0.tar.gz && \
    wget https://public-files.orthanc.team/third-party-downloads/vuejs-2.6.10.tar.gz && \
    wget https://public-files.orthanc.team/third-party-downloads/VTK-7.1.1.tar.gz && \
    wget https://public-files.orthanc.team/third-party-downloads/zlib-1.3.1.tar.gz

# for python and java plugin
RUN pip install pystache --break-system-packages

COPY build-or-download.sh /scripts
