on:
  workflow_call:
    inputs:
      is_tag:
        description: 'Is a Git Tag'
        required: true
        type: boolean
      current_branch_tag:
        description: 'Git branch or Tag'
        required: true
        type: string
      stable_unstalbe:
        description: 'stable/unstable'
        required: true
        type: string

jobs:

  build-windows-installer:
    name: build-windows-installer
    runs-on: "ubuntu-latest"

    steps:
    
    - name: Build installer
      run: ./ciBuildWindowsInstaller.sh ${{ inputs.is_tag }} ${{ inputs.current_branch_tag }}
      working-directory: ./WindowsInstaller
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
