name: nightly-osx-branch-builds

# on:
#   schedule:
#     - cron: "0 * * * *"

on:
  push:
    branches: 
      - 'nightly-builds'

jobs:

  build-osx-branches:
    name: build-osx-branches
    runs-on: "macos-latest"
    strategy:
      fail-fast: false
      matrix:
        config:
        # - {
        #     name: "Orthanc", 
        #     repo: "https://hg.orthanc-server.com/orthanc/",
        #     branch: "default",
        #     sourcesSubPath: "/OrthancServer",
        #     artifact: "Orthanc",
        #     artifact2: "libModalityWorklists.dylib",
        #     artifact3: "libServeFolders.dylib",
        #     artifact4: "libConnectivityChecks.dylib",
        #     extraCMakeFlags: "",
        #     unitTests: "./UnitTests"
        #   },
        - {
            name: "Orthanc-tcia", 
            repo: "https://hg.orthanc-server.com/orthanc-tcia/",
            branch: "default",
            sourcesSubPath: "",
            artifact: "libOrthancTcia.dylib",
            extraCMakeFlags: "",
            unitTests: "None"
          }

    steps:

    - name: Build if required
      id: build
      run: |
        brew install mercurial
        ./build-osx-branch.sh --repo ${{matrix.config.repo}} --branch ${{matrix.config.branch}} --workspace ${{github.workspace}} --sourceSubPath ${{matrix.config.sourcesSubPath}} --unitTests $${{matrix.config.unitTests}} --extraCMakeFlags $${{matrix.config.extraCMakeFlags}} --artifact $${{matrix.config.artifact}} --artifact1 $${{matrix.config.artifact1}} --artifact2 $${{matrix.config.artifact2}} --artifact3 $${{matrix.config.artifact3}} --artifact4 $${{matrix.config.artifact4}}
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

